//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKR_ResortServiceTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PKR_ResortServiceTest.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PKR_ResortServiceTest.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PKR_ResortServiceTest.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PKR_ResortServiceTest.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PKR_ResortTableContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class PKR_ResortTableContract : PKR_ResortServiceTest.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime parmAcquisitionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmRegistryNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmResortGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmResortIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmResortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PKR_ResortServiceTest.PKR_ResortTypeCostwise parmResortTypeCostwiseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmResortTypeLocationwiseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime parmAcquisitionDate {
            get {
                return this.parmAcquisitionDateField;
            }
            set {
                if ((this.parmAcquisitionDateField.Equals(value) != true)) {
                    this.parmAcquisitionDateField = value;
                    this.RaisePropertyChanged("parmAcquisitionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmRegistryNum {
            get {
                return this.parmRegistryNumField;
            }
            set {
                if ((object.ReferenceEquals(this.parmRegistryNumField, value) != true)) {
                    this.parmRegistryNumField = value;
                    this.RaisePropertyChanged("parmRegistryNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmResortGroupId {
            get {
                return this.parmResortGroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parmResortGroupIdField, value) != true)) {
                    this.parmResortGroupIdField = value;
                    this.RaisePropertyChanged("parmResortGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmResortId {
            get {
                return this.parmResortIdField;
            }
            set {
                if ((object.ReferenceEquals(this.parmResortIdField, value) != true)) {
                    this.parmResortIdField = value;
                    this.RaisePropertyChanged("parmResortId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmResortName {
            get {
                return this.parmResortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmResortNameField, value) != true)) {
                    this.parmResortNameField = value;
                    this.RaisePropertyChanged("parmResortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PKR_ResortServiceTest.PKR_ResortTypeCostwise parmResortTypeCostwise {
            get {
                return this.parmResortTypeCostwiseField;
            }
            set {
                if ((this.parmResortTypeCostwiseField.Equals(value) != true)) {
                    this.parmResortTypeCostwiseField = value;
                    this.RaisePropertyChanged("parmResortTypeCostwise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string parmResortTypeLocationwise {
            get {
                return this.parmResortTypeLocationwiseField;
            }
            set {
                if ((object.ReferenceEquals(this.parmResortTypeLocationwiseField, value) != true)) {
                    this.parmResortTypeLocationwiseField = value;
                    this.RaisePropertyChanged("parmResortTypeLocationwise");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.SysOperationDataContractBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortMessageContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortTableContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.SysOperationDataContractBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortMessageContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortTableContract))]
    public partial class XppObjectBase : PKR_ResortServiceTest.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysOperationDataContractBase", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract))]
    public partial class SysOperationDataContractBase : PKR_ResortServiceTest.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parmCallIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parmSessionIdxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime parmSessionLoginDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parmCallId {
            get {
                return this.parmCallIdField;
            }
            set {
                if ((this.parmCallIdField.Equals(value) != true)) {
                    this.parmCallIdField = value;
                    this.RaisePropertyChanged("parmCallId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parmSessionIdx {
            get {
                return this.parmSessionIdxField;
            }
            set {
                if ((this.parmSessionIdxField.Equals(value) != true)) {
                    this.parmSessionIdxField = value;
                    this.RaisePropertyChanged("parmSessionIdx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime parmSessionLoginDateTime {
            get {
                return this.parmSessionLoginDateTimeField;
            }
            set {
                if ((this.parmSessionLoginDateTimeField.Equals(value) != true)) {
                    this.parmSessionLoginDateTimeField = value;
                    this.RaisePropertyChanged("parmSessionLoginDateTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PKR_ResortResortGroupChangeContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class PKR_ResortResortGroupChangeContract : PKR_ResortServiceTest.SysOperationDataContractBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PKR_ResortServiceTest.NoYes parmHideResortIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmResortGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmResortIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PKR_ResortServiceTest.NoYes parmHideResortId {
            get {
                return this.parmHideResortIdField;
            }
            set {
                if ((this.parmHideResortIdField.Equals(value) != true)) {
                    this.parmHideResortIdField = value;
                    this.RaisePropertyChanged("parmHideResortId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmResortGroupID {
            get {
                return this.parmResortGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.parmResortGroupIDField, value) != true)) {
                    this.parmResortGroupIDField = value;
                    this.RaisePropertyChanged("parmResortGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmResortID {
            get {
                return this.parmResortIDField;
            }
            set {
                if ((object.ReferenceEquals(this.parmResortIDField, value) != true)) {
                    this.parmResortIDField = value;
                    this.RaisePropertyChanged("parmResortID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PKR_ResortMessageContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class PKR_ResortMessageContract : PKR_ResortServiceTest.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PKR_ResortTypeCostwise", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PKR_ResortTypeCostwise : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Economy = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Luxury = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuperLuxury = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.contoso.com/PKR_ResortMS", ConfigurationName="PKR_ResortServiceTest.ResortServices")]
    public interface ResortServices {
        
        // CODEGEN: Generating message contract since message getResorts has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.contoso.com/PKR_ResortMS/ResortServices/getResorts", ReplyAction="http://schemas.contoso.com/PKR_ResortMS/ResortServices/getResortsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PKR_ResortServiceTest.Fault), Action="http://schemas.contoso.com/PKR_ResortMS/ResortServices/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PKR_ResortServiceTest.getResortsResponse getResorts(PKR_ResortServiceTest.getResorts request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.contoso.com/PKR_ResortMS/ResortServices/getResorts", ReplyAction="http://schemas.contoso.com/PKR_ResortMS/ResortServices/getResortsResponse")]
        System.Threading.Tasks.Task<PKR_ResortServiceTest.getResortsResponse> getResortsAsync(PKR_ResortServiceTest.getResorts request);
        
        // CODEGEN: Generating message contract since message changeResortGroup has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.contoso.com/PKR_ResortMS/ResortServices/changeResortGroup", ReplyAction="http://schemas.contoso.com/PKR_ResortMS/ResortServices/changeResortGroupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PKR_ResortServiceTest.Fault), Action="http://schemas.contoso.com/PKR_ResortMS/ResortServices/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PKR_ResortServiceTest.changeResortGroupResponse changeResortGroup(PKR_ResortServiceTest.changeResortGroup request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.contoso.com/PKR_ResortMS/ResortServices/changeResortGroup", ReplyAction="http://schemas.contoso.com/PKR_ResortMS/ResortServices/changeResortGroupResponse")]
        System.Threading.Tasks.Task<PKR_ResortServiceTest.changeResortGroupResponse> changeResortGroupAsync(PKR_ResortServiceTest.changeResortGroup request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResorts", WrapperNamespace="http://schemas.contoso.com/PKR_ResortMS", IsWrapped=true)]
    public partial class getResorts {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PKR_ResortServiceTest.CallContext CallContext;
        
        public getResorts() {
        }
        
        public getResorts(PKR_ResortServiceTest.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResortsResponse", WrapperNamespace="http://schemas.contoso.com/PKR_ResortMS", IsWrapped=true)]
    public partial class getResortsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PKR_ResortServiceTest.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.contoso.com/PKR_ResortMS", Order=0)]
        public PKR_ResortServiceTest.PKR_ResortTableContract[] result;
        
        public getResortsResponse() {
        }
        
        public getResortsResponse(PKR_ResortServiceTest.Infolog Infolog, PKR_ResortServiceTest.PKR_ResortTableContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changeResortGroup", WrapperNamespace="http://schemas.contoso.com/PKR_ResortMS", IsWrapped=true)]
    public partial class changeResortGroup {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PKR_ResortServiceTest.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.contoso.com/PKR_ResortMS", Order=0)]
        public PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract _contract;
        
        public changeResortGroup() {
        }
        
        public changeResortGroup(PKR_ResortServiceTest.CallContext CallContext, PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract _contract) {
            this.CallContext = CallContext;
            this._contract = _contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changeResortGroupResponse", WrapperNamespace="http://schemas.contoso.com/PKR_ResortMS", IsWrapped=true)]
    public partial class changeResortGroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PKR_ResortServiceTest.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.contoso.com/PKR_ResortMS", Order=0)]
        public PKR_ResortServiceTest.PKR_ResortMessageContract result;
        
        public changeResortGroupResponse() {
        }
        
        public changeResortGroupResponse(PKR_ResortServiceTest.Infolog Infolog, PKR_ResortServiceTest.PKR_ResortMessageContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ResortServicesChannel : PKR_ResortServiceTest.ResortServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResortServicesClient : System.ServiceModel.ClientBase<PKR_ResortServiceTest.ResortServices>, PKR_ResortServiceTest.ResortServices {
        
        public ResortServicesClient() {
        }
        
        public ResortServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResortServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResortServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResortServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PKR_ResortServiceTest.getResortsResponse PKR_ResortServiceTest.ResortServices.getResorts(PKR_ResortServiceTest.getResorts request) {
            return base.Channel.getResorts(request);
        }
        
        public PKR_ResortServiceTest.Infolog getResorts(PKR_ResortServiceTest.CallContext CallContext, out PKR_ResortServiceTest.PKR_ResortTableContract[] result) {
            PKR_ResortServiceTest.getResorts inValue = new PKR_ResortServiceTest.getResorts();
            inValue.CallContext = CallContext;
            PKR_ResortServiceTest.getResortsResponse retVal = ((PKR_ResortServiceTest.ResortServices)(this)).getResorts(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PKR_ResortServiceTest.getResortsResponse> PKR_ResortServiceTest.ResortServices.getResortsAsync(PKR_ResortServiceTest.getResorts request) {
            return base.Channel.getResortsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PKR_ResortServiceTest.getResortsResponse> getResortsAsync(PKR_ResortServiceTest.CallContext CallContext) {
            PKR_ResortServiceTest.getResorts inValue = new PKR_ResortServiceTest.getResorts();
            inValue.CallContext = CallContext;
            return ((PKR_ResortServiceTest.ResortServices)(this)).getResortsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PKR_ResortServiceTest.changeResortGroupResponse PKR_ResortServiceTest.ResortServices.changeResortGroup(PKR_ResortServiceTest.changeResortGroup request) {
            return base.Channel.changeResortGroup(request);
        }
        
        public PKR_ResortServiceTest.Infolog changeResortGroup(PKR_ResortServiceTest.CallContext CallContext, PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract _contract, out PKR_ResortServiceTest.PKR_ResortMessageContract result) {
            PKR_ResortServiceTest.changeResortGroup inValue = new PKR_ResortServiceTest.changeResortGroup();
            inValue.CallContext = CallContext;
            inValue._contract = _contract;
            PKR_ResortServiceTest.changeResortGroupResponse retVal = ((PKR_ResortServiceTest.ResortServices)(this)).changeResortGroup(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PKR_ResortServiceTest.changeResortGroupResponse> PKR_ResortServiceTest.ResortServices.changeResortGroupAsync(PKR_ResortServiceTest.changeResortGroup request) {
            return base.Channel.changeResortGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<PKR_ResortServiceTest.changeResortGroupResponse> changeResortGroupAsync(PKR_ResortServiceTest.CallContext CallContext, PKR_ResortServiceTest.PKR_ResortResortGroupChangeContract _contract) {
            PKR_ResortServiceTest.changeResortGroup inValue = new PKR_ResortServiceTest.changeResortGroup();
            inValue.CallContext = CallContext;
            inValue._contract = _contract;
            return ((PKR_ResortServiceTest.ResortServices)(this)).changeResortGroupAsync(inValue);
        }
    }
}
